local frame = CreateFrame("Frame", nil, UIParent)
frame:SetSize(50, 50)
frame:SetPoint("CENTER")
local editBox = CreateFrame("EditBox", nil, frame, "InputBoxTemplate")
editBox:SetPoint("CENTER")
editBox:SetSize(250, 50)
editBox:SetAutoFocus(false)
editBox:SetScript("OnEscapePressed", function(_)
  editBox:ClearFocus()
end)
editBox:SetScript("OnEnterPressed", function(_)
  editBox:SetPropagateKeyboardInput(true)
end)
editBox:SetScript("OnKeyDown", function(_)
  editBox:SetPropagateKeyboardInput(false)
end)
